name: emoji_transcoder
description: Encode messages into emojis and decode them using Unicode variation selectors.  Hide text within any Unicode character invisibly.
version: 0.0.2
homepage: https://github.com/cypherstack/emoji_transcoder
repository: https://github.com/cypherstack/emoji_transcoder
issue_tracker: https://github.com/cypherstack/emoji_transcoder/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

topics:
  - unicode
  - steganography
  - encoding
  - emoji
  - variation-selectors
